//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectBody.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class avoirRole
    {
        public int idRole { get; set; }
        public int idCoach { get; set; }
        public int idClient { get; set; }
        public int idSpecN { get; set; }
        public int idGestionnaire { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual coach coach { get; set; }
        public virtual gestionnaire gestionnaire { get; set; }
        public virtual role role { get; set; }
        public virtual specNutrition specNutrition { get; set; }
    }
}
