//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectBody.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class composer
    {
        public string nom { get; set; }
        public string label { get; set; }
        public int quentite { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        public virtual repas repas { get; set; }
    }
}
