//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectBody.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyFitBodyEntities : DbContext
    {
        public MyFitBodyEntities()
            : base("name=MyFitBodyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avoirRole> avoirRole { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<coach> coach { get; set; }
        public virtual DbSet<composer> composer { get; set; }
        public virtual DbSet<exercices> exercices { get; set; }
        public virtual DbSet<gestionnaire> gestionnaire { get; set; }
        public virtual DbSet<ingredients> ingredients { get; set; }
        public virtual DbSet<maladies> maladies { get; set; }
        public virtual DbSet<repas> repas { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<specNutrition> specNutrition { get; set; }
        public virtual DbSet<typeIngredient> typeIngredient { get; set; }
        public virtual DbSet<typeOfExercice> typeOfExercice { get; set; }
        public virtual DbSet<typeRepas> typeRepas { get; set; }
        public virtual DbSet<reponses> reponses { get; set; }
        public virtual DbSet<questions> questions { get; set; }
    }
}
